//! Wave B parity test — Rust equities features vs Python reference.
//!
//! Loads `engine/tests/fixtures/equity_feature_parity.json` (generated by
//! `training/equities_features.py --generate-fixture`) and verifies that the
//! Rust `compute_equity_features` matches the Python reference within 1e-6.
//!
//! To regenerate the fixture:
//!   python3 training/equities_features.py --generate-fixture
//!
//! The fixture carries per-bar timestamps; VIX/TLT are stored as
//! `(ts, close)` tuples and joined to QQQ **by timestamp** (see Deferred Fix 1),
//! so a missing macro bar zeroes the feature for that one candle only instead of
//! shifting the whole series.

use std::fs;

use engine::db::EquityCandle;
use engine::features::equities_v2::{compute_equity_features, EquityFeatureRow};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Fixture {
    input: FixtureInput,
    expected: Vec<ExpectedRow>,
}

#[derive(Debug, Deserialize)]
struct FixtureInput {
    opens: Vec<f64>,
    highs: Vec<f64>,
    lows: Vec<f64>,
    closes: Vec<f64>,
    volumes: Vec<f64>,
    ts: Vec<i64>,
    vix: Vec<[i64; 2]>,
    tlt: Vec<[i64; 2]>,
}

#[derive(Debug, Deserialize)]
struct ExpectedRow {
    timestamp: i64,
    trend_slope: f64,
    trend_adx: f64,
    rsi_14: f64,
    vix_regime: f64,
    tlt_corr_20d: f64,
    rvol_20d: f64,
    gap_pct: f64,
    drawdown_from_50d_high: f64,
}

impl ExpectedRow {
    fn to_feature_row(&self) -> EquityFeatureRow {
        EquityFeatureRow {
            timestamp: self.timestamp,
            trend_slope: self.trend_slope,
            trend_adx: self.trend_adx,
            rsi_14: self.rsi_14,
            vix_regime: self.vix_regime,
            tlt_corr_20d: self.tlt_corr_20d,
            rvol_20d: self.rvol_20d,
            gap_pct: self.gap_pct,
            drawdown_from_50d_high: self.drawdown_from_50d_high,
        }
    }
}

fn load_fixture() -> Fixture {
    // CARGO_MANIFEST_DIR is the engine/ crate dir; the fixture lives under
    // tests/fixtures/ relative to it.
    let manifest = env!("CARGO_MANIFEST_DIR");
    let path = std::path::Path::new(manifest)
        .join("tests/fixtures/equity_feature_parity.json");
    let text = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read fixture {}: {e}", path.display()));
    serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("failed to parse fixture JSON: {e}"))
}

fn build_candles(input: &FixtureInput) -> Vec<EquityCandle> {
    let n = input.closes.len();
    (0..n)
        .map(|i| EquityCandle {
            symbol: "QQQ".to_string(),
            ts: input.ts[i],
            open: input.opens[i],
            high: input.highs[i],
            low: input.lows[i],
            close: input.closes[i],
            volume: input.volumes[i] as i64,
            source: "yahoo".to_string(),
        })
        .collect()
}

fn as_pairs(rows: &[[i64; 2]]) -> Vec<(i64, f64)> {
    rows.iter().map(|r| (r[0], r[1])).collect()
}

const TOLERANCE: f64 = 1e-6;

#[test]
fn rust_vs_python_feature_parity() {
    let fixture = load_fixture();
    let candles = build_candles(&fixture.input);
    let vix: Vec<(i64, f64)> = as_pairs(&fixture.input.vix);
    let tlt: Vec<(i64, f64)> = as_pairs(&fixture.input.tlt);

    let rust_rows =
        compute_equity_features(&candles, Some(&vix), Some(&tlt));

    assert_eq!(
        rust_rows.len(),
        fixture.expected.len(),
        "row count mismatch: rust={} expected={}",
        rust_rows.len(),
        fixture.expected.len()
    );

    let feature_names = [
        "trend_slope",
        "trend_adx",
        "rsi_14",
        "vix_regime",
        "tlt_corr_20d",
        "rvol_20d",
        "gap_pct",
        "drawdown_from_50d_high",
    ];

    let mut max_diff = 0.0_f64;
    let mut mismatches = Vec::new();

    for (i, (rust, expected)) in rust_rows.iter().zip(fixture.expected.iter()).enumerate() {
        let rust_arr = rust.to_array();
        let exp_arr = expected.to_feature_row().to_array();

        for (j, (&r, &e)) in rust_arr.iter().zip(exp_arr.iter()).enumerate() {
            let diff = (r - e).abs();
            if diff > max_diff {
                max_diff = diff;
            }
            if diff > TOLERANCE {
                mismatches.push(format!(
                    "row={} feature={} rust={:.10} python={:.10} diff={:.2e}",
                    i, feature_names[j], r, e, diff
                ));
            }
        }
    }

    if !mismatches.is_empty() {
        let report = mismatches
            .iter()
            .take(10)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n");
        panic!(
            "PARITY FAILED: {} mismatches (max_diff={max_diff:.2e}, tol={TOLERANCE:.0e})\nFirst 10:\n{report}",
            mismatches.len()
        );
    }

    // Also report which feature had the largest diff (informational).
    eprintln!(
        "PARITY OK: {} rows x {} features, max_diff={max_diff:.2e} (tol={TOLERANCE:.0e})",
        rust_rows.len(),
        feature_names.len(),
    );
}

#[test]
fn fixture_has_all_8_features() {
    let fixture = load_fixture();
    assert!(!fixture.expected.is_empty(), "fixture should have rows");
    // Verify all 8 feature fields are present in the first expected row.
    let row = &fixture.expected[0];
    let _ = (
        row.trend_slope,
        row.trend_adx,
        row.rsi_14,
        row.vix_regime,
        row.tlt_corr_20d,
        row.rvol_20d,
        row.gap_pct,
        row.drawdown_from_50d_high,
    );
}
